# Stubs for cachecontrol.serialize (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .compat import HTTPResponse as HTTPResponse, pickle as pickle, text_type as text_type

class Serializer:
    def dumps(self, request, response, body=None): ...
    def loads(self, request, data): ...
    def prepare_response(self, request, cached): ...
